"""empty message

Revision ID: 960f33d7793b
Revises: ab1d33295055
Create Date: 2022-06-20 18:28:10.628324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960f33d7793b'
down_revision = 'ab1d33295055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows_count')
    op.drop_column('Venue', 'past_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
